--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VennDev/TestAsyncPlugin
build-by-default: true
branches:
- main
projects:
  TestAsyncPlugin:
    lint:
      phpstan: false
      syntaxError: false
    path: ""
...
